"""Изменение схемы таблицы parcels

Revision ID: 21606d508e61
Revises: 9b8d3d4a1c01
Create Date: 2026-07-31 19:39:48.893262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21606d508e61'
down_revision: Union[str, Sequence[str], None] = '9b8d3d4a1c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('delivery_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.drop_column('parcels', 'delivery_price_rub')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcels', sa.Column('delivery_price_rub', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_column('parcels', 'delivery_price')
    # ### end Alembic commands ###
