"""Initial migration

Revision ID: 804decd45398
Revises: 
Create Date: 2026-08-11 18:10:47.180387

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '804decd45398'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('parcels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('content_price_usd', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('parcel_type_id', sa.Integer(), nullable=False),
    sa.Column('delivery_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_type_id'], ['parcel_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_session_id'), 'parcels', ['session_id'], unique=False)
    op.create_index('ix_parcels_session_type', 'parcels', ['session_id', 'parcel_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_parcels_session_type', table_name='parcels')
    op.drop_index(op.f('ix_parcels_session_id'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_table('parcel_types')
    # ### end Alembic commands ###
